### ISSUE TITLE
Link XML của MP3 Zing đã thay đổi

### ISSUE THREAD

**Issue by trongthanh** [naustudio/nau-jukebox#11]
Cần viết lại parser / cách chơi file mp3 để workaround link MP3 theo format mới của Zing.

**Comment by tam-pham-alpha** [comment]
@tttt-conan Tùng đang fix cái này phải hơm

**Comment by trongthanh** [comment]
Note lại lưu ý mà mình đã tìm hiểu:
- Cái link mp3 trong html5xml nó kiểm tra cookie, nếu cookie ko hợp lệ sẽ trả về 403 forbidden
- Còn 1 cách là lưu cái file songxml luôn, mỗi lần play thì phía client sẽ fetch cái link XML đó để lấy mp3 source 
- Phía client khi lấy songxml sẽ như là client vào trang mp3 zing để chơi nhạc nên sẽ có vết cookie đầy đủ
- Vì NCT và mp3 có cho nhúng player ra ngoài nên may là file xml của nó ko bị chặn CORS
- Cơ chế mới này sẽ fix đc lỗi link NCT hết hạn sau 24h luôn. #1

**Comment by trongthanh** [comment]
I think we'd better do #24 to fix this issue. It's simpler and avoid cross domain problems on client side.
