### ISSUE TITLE
Thêm tính năng NÂU coin

### ISSUE THREAD

**Issue by tam-pham-alpha** [naustudio/nau-jukebox#14]
Tính năng này cho phép người chơi sẽ đổi VND qua NÂU coin thông qua nhà cái (HOST).

**Comment by tam-pham-alpha** [comment]
I am going to do this

**Comment by trongthanh** [comment]
Is this task done yet? Is there anything else needed to be done?

**Comment by tam-pham-alpha** [comment]
Yup, this issue has been done, I will close it now.
