### ISSUE TITLE
Feature: Move featching status to top

### ISSUE THREAD

**Issue by tam-pham-alpha** [naustudio/nau-jukebox#3]
Currently, when I rebook a song, I cannot see current fetching status. It's better to create a loading at top, next to the header.

**Comment by trongthanh** [comment]
Good point. I intend to move the floating player to top like itunes. There we can add add some notification and indicators.

**Comment by tam-pham-alpha** [comment]
I can do it for you :))

**Comment by trongthanh** [comment]
@tampham47 Please help with this implementation. 

My vision is that we'll move the sticky bar to top and embed the input field and the brand "Nau Jukebox" in there. The brand name and the player now can be less prominent. Player bar can be shorter to allow room for the input field. Let's see how they can fit into the sticky bar.

**Comment by tam-pham-alpha** [comment]
@trongthanh it's very clear, I will handle this enhancement. :))
