### ISSUE TITLE
Zing json data use Array for multiple artists

### ISSUE THREAD

**Issue by trongthanh** [naustudio/nau-jukebox#45]
Zing json data has switch for Array to represent group of artists for a song. Example:

```json
{
  "artists": [
    {
      "name": "Tiêu Châu Như Quỳnh",
      "link": "/nghe-si/Tieu-Chau-Nhu-Quynh"
    },
    {
      "name": " Lam Trường",
      "link": "/nghe-si/Lam-Truong"
    }
  ]
}
```

Need to discuss whether we move our data structure to this format for artist, or concatenate them into a comma-separated string.

**Comment by trongthanh** [comment]
Join the name of artists in a comma separated list. e.g `Tiêu Châu Như Quỳnh, Lam Trường`.

Make sure the names are trimmed before concatenate.

**Comment by erictran308** [comment]
Done. Implemented at commit: https://github.com/naustudio/nau-jukebox/commit/791608ff31f3febfd5c7ec66dfda4cecbe18a3a9
