### ISSUE TITLE
Zing: no thumbnail songs prevented from adding to list 

### ISSUE THREAD

**Issue by trongthanh** [naustudio/nau-jukebox#50]
New strict schema block the songs which lack thumbUrl field from being added. We need to check for this field and use fallback URL.

Example: https://mp3.zing.vn/bai-hat/Vo-Do-Vy-Hanh-Ho/IWBU0EIF.html

**Comment by erictran308** [comment]
Done, fixed at commit: https://github.com/naustudio/nau-jukebox/commit/065ccd00f12f0e4aeaf40a203ec858bb424c3d16
